name: fetch list from ethereum-lists/chains

on:
  schedule:
    - cron: "0 6 * * *" # “At 6:00 everyday”
  workflow_dispatch:

jobs:
  fetch:
    name: fetch ethereum-lists/chains
    runs-on: ubuntu-latest
    steps:
      - name: fetch myself
        uses: actions/checkout@v2
        with:
          path: self

      - name: fetch template
        uses: actions/checkout@v2
        with:
          repository: ethereum-lists/chains
          path: ethereum-lists

      - name: copy file into src
        run: |
          rm -rf ./self/src/data
          mkdir -p ./self/src/data
          cp -rf ./ethereum-lists/_data/* ./self/src/data

      - name: check for modified files
        id: git-check
        working-directory: ./self
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: commit to main branch
        if: steps.git-check.outputs.modified == 'true'
        working-directory: ./self
        run:  |
          git config --global user.name 'bot'
          git config --global user.email 'bot@mail.com'
          git add -A
          git commit -m 'feat(data): fetch list from ethereum-lists/chains'
          git push
